import { Script } from '../../toolchain/types/script/script';
import { ScriptConfig } from '../gen/spec_config'; /* File will be automatically generated by compiler! Run "nom run cli install" */
import { Instance } from './main';

export class MyScript implements Script.Class<ScriptConfig> {

    private instance: Instance | undefined;

    start = async (ctx: Script.Context, config: ScriptConfig): Promise<void> => {
        this.instance = new Instance(ctx, config);
        return this.instance.start();
    }

    stop = async (reason: Script.StopReason): Promise<void> => {
        return this.instance?.stop(reason);
    }
}

export const script = new MyScript();